In [101]:
import numpy as np
import random
import warnings

warnings.filterwarnings('ignore')

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(4,2.5)

array([2.5, 2.5, 2.5, 2.5])

In [5]:
np.arange(-5,5,1.5)

array([-5. , -3.5, -2. , -0.5,  1. ,  2.5,  4. ])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
micky = np.array([1,2,3,4])
micky

array([1, 2, 3, 4])

In [8]:
micky[2] = 10
micky

array([ 1,  2, 10,  4])

In [9]:
meddy = np.linspace(1,5,3)
nani = np.arange(1,5,3)
print(meddy)
print(nani)

[1. 3. 5.]
[1 4]


In [10]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
micky = np.array(([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]))
micky[1][2]

6

In [12]:
meddy = micky * 2
meddy

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [13]:
micky >= 5

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [14]:
micky >= meddy

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [15]:
micky[micky>5]

array([6, 7, 8, 9])

In [16]:
random.seed(42)
nani = np.random.randn(5,2)
nani

array([[ 0.2791345 ,  0.16963214],
       [ 0.08704788, -0.48714012],
       [-0.29665533,  0.07532488],
       [-1.79713429,  0.76686731],
       [-0.57281357,  0.60647481]])

In [17]:
print(nani.sum())
print(nani.max())
print(nani.min())
print(nani.mean())
print(nani.std())

-1.1692617815352726
0.7668673146448509
-1.7971342947477276
-0.11692617815352727
0.694423438065538


In [68]:
np.random.seed(1)
a = np.random.randint(low=1,high=5,size=(1,3))
b = np.random.randint(low=1,high=5,size=(1,3))
a = np.array(a)
b = np.array(b)
c = np.array([
    [1,0],
    [1,1],
    [1,1]
    ])
d = np.array([
    [2,0],
    [3,1],
    [4,1]
    ])
e = np.array([1,2,3,4])
f = np.array([8,0,0,3])

In [87]:
def dot_product(u,v):
    if u.shape != v.shape:
        return "They are not of the same shape!!!"

    result = 0
    size = u.shape[0]
    if len(u.shape) == 1:
        for i in range(size):
            result += u[i] * v[i]
    else:
        for i in range(size):
            result += dot_product(u[i],v[i])

    return result


In [88]:
def cross_product (u,v):
    num_row_u = u.shape[0]
    num_row_v = v.shape[0]
    num_col_u = u.shape[1]
    num_col_v = v.shape[1]

    result = np.zeros((num_row_u,num_col_v))

    if num_col_u == num_row_v:
        for row in range(num_row_u):
            for col in range(num_col_v):
                result[row][col] = dot_product(u[row],v[:,col])
        
        return result
    
    else:
        return print("The vectors can't be multiplied")

In [89]:
dot_product(e,f)

20

In [90]:
a = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
    ])
b = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

print(a.shape)
print(b.shape)

(3, 4)
(4, 3)


In [111]:
cross_prd = cross_product(a,b)
cross_prd

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [108]:
cross_prd_inv = np.linalg.inv(cross_prd)
cross_prd_inv

array([[-0.15,  0.91, -0.29],
       [ 0.26, -0.8 ,  0.07],
       [-0.16,  0.25,  0.21]])

In [113]:
np.set_printoptions(precision=3)
np.round(cross_product(cross_prd,cross_prd_inv))

array([[ 1., -0., -0.],
       [ 0.,  1.,  0.],
       [ 0., -0.,  1.]])